### PR TITLE
Added CERN OHL LICENSE file

### PR DESCRIPTION
**Pull request by pedrominatel**
CERN OHL license version 2 file added to the project.

Closes: https://github.com/esp-rs/esp-rust-board/issues/5

### CODE REVIEW

**Comment by pedrominatel** [comment]
I've added the strongly-reciprocal variant of CERN-OHL, but we can use a different variant.

https://ohwr.org/project/cernohl/wikis/Documents/CERN-OHL-version-2

**Comment by 0Grit** [comment]
#5

**Comment by pedrominatel** [comment]
I cant add you as reviewer @0Grit, but I really appreciate your feedback!

**Comment by 0Grit** [comment]
I'm less versed in OHL than @beriberikix and @chrisgammell

**Review by jessebraham — APPROVED** [review]
Seems like a good choice to me!

**Review by MabezDev — APPROVED** [review]

**Comment by TheButlah** [comment]
#31

**Pull request merged**
